### ISSUE TITLE
ldap connection

### ISSUE THREAD

**Issue by xgodon** [fjudith/docker-squash-tm#2]
hello,

i ran squash with : 

-e LDAP_ENABLED=true \
-e LDAP_PROVIDER="ldap" \
-e LDAP_URL=ldap://x.x.x.x:389 \
-e LDAP_SECURITY_MANAGERDN="uid=usquash,ou=People,dc=exemple,dc=local" \
-e LDAP_SECURITY_MANAGERPASSWORD="passwd" \
-e LDAP_FETCH_ATTRIBUTES=true \
-e LDAP_USER_DNPATTERNS="example=uid={0},ou=people" \

but i got : 

[17-04-24 11:37:28.911] SquashTM - 95 ERROR [localhost-startStop-1] [] --- org.springframework.boot.SpringApplication: Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userAdministrationController': Unsatisfied dependency expressed through field 'authenticationProviderContext': Error creating bean with name 'authenticationProviderContext': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Features for authentication provider named 'ldap' not available; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticationProviderContext': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Features for authentication provider named 'ldap' not available

**Comment by uZer** [comment]
Same here!
Did you find the reason @xgodon?

EDIT:
Ok I just realised it might be a premium plugin you have to pay for...

**Comment by fjudith** [comment]
hello @uZer ,

That's right.

This image has been initially built with Prenium plugins.

Will update the documentation accordingly
